### ISSUE TITLE
3x3 NashEqFinder

### ISSUE THREAD

**Issue by HichamDvlp** [ChihabEddine98/NashEqFinder#1]
Hello, I hope you're well, I just wanted to know if you have a 3x3 NashEqFinder, cause I've tried to do it myself but i keep getting errors and i don't know what's the problem exactly.
If you can provide it that would be great or if you can help me do it, i would really appreciate it.
Have a nice day.

**Comment by ChihabEddine98** [comment]
Hey Hicham , I can help you make the 3x3 version but are you looking for the pure strategies NE or the mixed one ?

Best,

**Comment by HichamDvlp** [comment]
just the pure one, i need it before 1 PM if you can help.
Thanks.

**Comment by ChihabEddine98** [comment]
I think the GUI would be a bit complicated to be done before 1PM If you need the command line version I can try to provide a solution indeed

**Comment by HichamDvlp** [comment]
that would be heplful, yes

**Comment by ChihabEddine98** [comment]
Hey, I've just released the 3x3 command line version you can find it here, please fill free to contribute for any bugs (they may be there 🪲) or any question ! [see this code](https://github.com/ChihabEddine98/NashEqFinder/commit/51d7d26b91dae58f8d20040655942d93ca32feb5)
